# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Free Responsive Bootstrap Theme and Templates
description: > # this means to ignore newlines until "baseurl:"
  Free HTML Themes and Templates for speedup your Bootstrap 4 web 
  development with minimal design and lightweight coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://BootstrapJet.com" # the base hostname & protocol for your site
github_username:  gitShot


permalink: /:categories/:title.html

# Build settings
markdown: kramdown

collections:
  themes:
    output: true